name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"



jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env: 
      WORKSPACE: ${{github.workspace}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
      - name: Run GoReleaser
        run: |
         go install github.com/goreleaser/goreleaser@latest
         curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
         curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.49.1
         make release
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          make build
          docker build . --tag ghcr.io/supply-chain-security:latest
          syft ghcr.io/supply-chain-security:latest -o cyclonedx-json > supply-chain-security.cdx
          COSIGN_EXPERIMENTAL=1 cosign attest --predicate ghcr.io/supply-chain-security.cdx supply-chain-security:latest
          docker push ghcr.io/supply-chain-security:latest
      
          