name: ko-build-release

on:
  pull_request:
  push:

jobs:
  ko-build-release:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.release-image.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0 
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: ko-build/setup-ko@v0.6
      - name: Publish 
        id: release-image
        uses: ./.github/actions/publish
        with:
          makefile-target: ko-build
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository_owner }}
          version: ${{ github.ref_name }}
          sign-image: true
          sbom-name: supply-chain-security
          sbom-repository: ghcr.io/${{ github.repository_owner }}/sbom
          signature-repository: ghcr.io/${{ github.repository_owner }}/signatures
          main-path: ./cmd/supply-chain-security
      
  provenance:
    needs: [ko-build-release]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
    with:
      image: ghcr.io/${{github.repository}}
        # The image digest is used to prevent TOCTOU issues.
        # This is an output of the docker/build-push-action
        # See: https://github.com/slsa-framework/slsa-verifier#toctou-attacks
      digest: ${{ needs.ko-build-release.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}